remote_theme: just-the-docs/just-the-docs
title: Dev Notes
description: Technical notes and tutorials


color_scheme: dark
search_enabled: true
footer_content: "Made by <a href='https://github.com/gatisr'>@gatisr</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%H:%M %d.%m.%Y"  # 10:19 12.02.2026